version: '2'
services:
  zookeeper:
    container_name: local-zookeeper
    image: bitnami/zookeeper:3.7.1-debian-11-r36
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
  kafka:
    container_name: local-kafka
    hostname: kafka-server
    image: bitnami/kafka:2.8.0
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock